# Generated by Django 5.2.6 on 2025-09-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachersManagement", "0002_teacherprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
