# Generated by Django 5.2.5 on 2025-09-13 07:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachersManagement', '0003_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('estimated_effort', models.PositiveSmallIntegerField(help_text='Estimated effort (hours per week).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('lesson_credits', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('lesson_designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='teachersManagement.teacherprofile')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='lesson_management.lesson')),
            ],
            options={
                'ordering': ['unit_code'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lesson_management.lesson')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status'], name='lesson_mana_status_afc159_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['unit_code'], name='lesson_mana_unit_co_26cebd_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='lesson_mana_due_dat_6d3ad3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('lesson', 'title')},
        ),
    ]
