# Generated by Django 5.2.5 on 2025-10-03 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson_management", "0002_lessonenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="youtube_link",
            field=models.URLField(
                blank=True, help_text="YouTube video URL for this lesson"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="youtube_thumbnail",
            field=models.URLField(
                blank=True,
                help_text="YouTube thumbnail URL (auto-generated from video link)",
            ),
        ),
        migrations.CreateModel(
            name="ReadingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Optional URL for the reading material"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_list",
                        to="lesson_management.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
                "unique_together": {("lesson", "title")},
            },
        ),
    ]
