# Generated by Django 5.2.5 on 2025-10-04 09:06

import django.core.validators
import django.db.models.deletion
import lesson_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_management', '0003_lesson_youtube_link_lesson_youtube_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=lesson_management.models.assignment_attachment_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lesson_management.assignment')),
            ],
        ),
    ]
