# Generated by Django 5.2.5 on 2025-10-03 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lesson_management",
            "0003_lesson_youtube_link_lesson_youtube_thumbnail_and_more",
        ),
        ("student_management", "0005_enrollmentsequence_alter_student_course_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingListProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="lesson_management.readinglist",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to="student_management.student",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student"], name="lesson_mana_student_4de0cf_idx"
                    ),
                    models.Index(
                        fields=["reading"], name="lesson_mana_reading_1a7291_idx"
                    ),
                ],
                "unique_together": {("student", "reading")},
            },
        ),
        migrations.CreateModel(
            name="VideoProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_progress",
                        to="lesson_management.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_progress",
                        to="student_management.student",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student"], name="lesson_mana_student_590fdd_idx"
                    ),
                    models.Index(
                        fields=["lesson"], name="lesson_mana_lesson__8bd96c_idx"
                    ),
                ],
                "unique_together": {("student", "lesson")},
            },
        ),
    ]
