# Generated by Django 5.2.6 on 2025-10-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_management', '0004_assignmentattachment'),
        ('lesson_management', '0004_readinglistprogress_videoprogress'),
    ]

    operations = [
    ]
