# Generated by Django 5.2.6 on 2025-10-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_management', '0005_merge_20251007_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='youtube_thumbnail',
            field=models.URLField(blank=True, help_text='Auto-generated from YouTube link'),
        ),
    ]
