# Generated by Django 5.2.5 on 2025-10-17 07:33

import django.core.validators
import lesson_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson_management", "0007_assignmentsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="pdf",
            field=models.FileField(
                blank=True,
                help_text="Assignment PDF file (optional)",
                null=True,
                upload_to=lesson_management.models.assignment_pdf_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="weightage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Weightage percentage (0-100). Total weightage of all assignments in a lesson should be 100.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
