# Generated by Django 5.2.5 on 2025-10-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson_management", "0008_assignment_pdf_assignment_weightage"),
        ("student_management", "0006_alter_student_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonCreditAwarded",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("credits_amount", models.PositiveSmallIntegerField()),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits_awarded",
                        to="lesson_management.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_credits_awarded",
                        to="student_management.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-awarded_at"],
                "indexes": [
                    models.Index(fields=["student"], name="lesson_mana_student_9faeaa_idx"),
                    models.Index(fields=["lesson"], name="lesson_mana_lesson__3bb124_idx"),
                ],
                "unique_together": {("student", "lesson")},
            },
        ),
    ]
