# Generated by Django 5.2.5 on 2025-10-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson_management", "0009_lessoncreditawarded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lesson_credits",
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
