# Generated by Django 5.2.6 on 2025-09-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0004_remove_student_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_number",
            field=models.BigIntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="year_of_study",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
