# Generated by Django 5.2.5 on 2025-10-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0005_enrollmentsequence_alter_student_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("reactive", "Reactivated Enrollment"), ("dropout", "Dropped Out")],
                default="active",
                max_length=20,
            ),
        ),
    ]
