# Generated by Django 5.2.5 on 2025-10-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assist", "0003_vector_index"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentchunk",
            new_name="assist_docu_lesson__9efbd5_idx",
            old_name="assist_docu_lesson__a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="studentquestion",
            new_name="assist_stud_user_id_5cb6c0_idx",
            old_name="assist_stud_user_id_d4e5f6_idx",
        ),
    ]
