# Generated by Django 5.2.6 on 2025-09-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_management", "0002_alter_course_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="total_credits_required",
            field=models.PositiveIntegerField(default=144),
        ),
    ]
