# Generated by Django 5.2.5 on 2025-09-23 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_management", "0003_course_total_credits_required"),
        ("lesson_management", "0002_lessonenrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of lesson in course"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this lesson is required for course completion",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_lessons",
                        to="course_management.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_courses",
                        to="lesson_management.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "lesson__unit_code"],
                "unique_together": {("course", "lesson")},
            },
        ),
    ]
