# Generated by Django 5.2.5 on 2025-10-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0004_courselesson'),
        ('lesson_management', '0002_lessonenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='courses', through='course_management.CourseLesson', to='lesson_management.lesson'),
        ),
    ]
