# Generated by Django 5.2.5 on 2025-10-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_management", "0004_courselesson"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={},
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["name"], name="course_mana_name_39a8a1_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["code"], name="course_mana_code_849f8b_idx"),
        ),
    ]
