# Generated by Django 5.2.5 on 2025-10-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0005_alter_course_options_and_more'),
        ('course_management', '0005_course_lessons'),
    ]

    operations = [
    ]
