# Generated by Django 5.2.6 on 2025-10-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0006_course_director'),
        ('course_management', '0006_merge_20251003_2125'),
    ]

    operations = [
    ]
