# Generated by Django 5.2.5 on 2025-10-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "course_management",
            "0007_merge_0006_course_director_0006_merge_20251003_2125",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="director_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
