"""
Django settings for NotMoodle project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Load environment variables from project root .env if present
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-@(4__%y!%h()7$u53j4l9+7iqn(yf#hs6xzuefj1@+5@rol!z&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Social auth
    "social_django",
    
    
    'teachersManagement',
    "student_management",
    "welcome_page",
    "lesson_management",
    "course_management",
    "classroom_and_grading",
    "assist",  # NotMoodle AI Assistant
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "NotMoodle.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # social auth context
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

WSGI_APPLICATION = "NotMoodle.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Automatic database configuration with PostgreSQL fallback to SQLite
# - If PostgreSQL is available: Use it (enables AI assistant with pgvector)
# - If PostgreSQL is not available: Use SQLite (all features work except AI assistant)

def get_database_config():
    """
    Automatically detect database availability and configure accordingly.
    
    Returns:
        dict: Database configuration for Django settings
    """
    # Check if we should force SQLite (useful for testing)
    if os.getenv("USE_SQLITE", "").lower() == "true":
        print("🗄️  Database: SQLite (forced by USE_SQLITE environment variable)")
        return {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }
    
    # Try PostgreSQL configuration
    DB_NAME = os.getenv("DB_NAME", "notmoodle_db")
    DB_USER = os.getenv("DB_USER", "postgres")
    DB_PASSWORD = os.getenv("DB_PASSWORD", "")
    DB_HOST = os.getenv("DB_HOST", "localhost")
    DB_PORT = os.getenv("DB_PORT", "5432")
    
    # Test PostgreSQL connection
    try:
        import psycopg2
        conn = psycopg2.connect(
            dbname=DB_NAME,
            user=DB_USER,
            password=DB_PASSWORD,
            host=DB_HOST,
            port=DB_PORT,
            connect_timeout=3
        )
        conn.close()
        print("🐘 Database: PostgreSQL (AI assistant enabled with pgvector)")
        return {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": DB_NAME,
                "USER": DB_USER,
                "PASSWORD": DB_PASSWORD,
                "HOST": DB_HOST,
                "PORT": DB_PORT,
            }
        }
    except Exception as e:
        print(f"⚠️  PostgreSQL not available ({e})")
        print("🗄️  Database: SQLite fallback (all features work except AI assistant)")
        return {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }

DATABASES = get_database_config()

# Store database type for feature detection
USING_POSTGRESQL = DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_URL = "teachersManagement:teacher_login"
LOGIN_REDIRECT_URL = "teachersManagement:teacher_home"
LOGOUT_REDIRECT_URL = "teachersManagement:teacher_login"

# Helpful in dev: allow common localhost origins
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://127.0.0.1:8001",
    "http://localhost:8001",
    "http://127.0.0.1:8080",
    "http://localhost:8080",
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Project-level static directory for shared assets (images, global styles)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---- Social Authentication (Google) ----
AUTHENTICATION_BACKENDS = (
    "social_core.backends.google.GoogleOAuth2",
    "django.contrib.auth.backends.ModelBackend",
)

# Client ID/Secret: configure via environment variables for safety
# ALWAYS load .env file first to ensure it takes precedence over system environment variables
load_dotenv(BASE_DIR / ".env", override=True)

# Get credentials from .env file (will use fallback if .env doesn't exist)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv(
    "GOOGLE_OAUTH2_CLIENT_ID",
    "942961813473-vi0lhvaqfdt390v11j8vnq41rbqttk7f.apps.googleusercontent.com",
)
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv("GOOGLE_OAUTH2_CLIENT_SECRET", "")

# Debug: Print which credentials are being used (remove in production)
if DEBUG:
    print(f"Using Google OAuth Client ID: {SOCIAL_AUTH_GOOGLE_OAUTH2_KEY[:20]}...")
    print(f"Using Google OAuth Secret: {'Yes' if SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET else 'No'}")

# Redirect URLs
LOGIN_URL = "welcome_page:login"
LOGIN_REDIRECT_URL = "student_management:student_dashboard"
LOGOUT_REDIRECT_URL = "welcome_page:welcome_page"

# Social auth pipeline: include default and create student profile if missing
SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.user.create_user",
    # Associate the social account with the user
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    # Custom: ensure a Student profile exists
    "student_management.pipeline.create_student_profile",
)

# Local dev helpers
SOCIAL_AUTH_REDIRECT_IS_HTTPS = False

# Redirect any social-auth errors (e.g., AuthCanceled) to a 404 page route
SOCIAL_AUTH_RAISE_EXCEPTIONS = False
SOCIAL_AUTH_LOGIN_ERROR_URL = "/404/"
SOCIAL_AUTH_DISCONNECT_ERROR_URL = "/404/"

MEDIA_RUL = "/meida"

# ---- NotMoodle AI Assistant (Ollama + RAG) ----
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
AI_CHAT_MODEL = os.getenv("AI_CHAT_MODEL", "llama3.1:latest")
AI_EMBED_MODEL = os.getenv("AI_EMBED_MODEL", "nomic-embed-text")
AI_DAILY_QUESTION_LIMIT = int(os.getenv("AI_DAILY_QUESTION_LIMIT", "100"))

MEDIA_ROOT = BASE_DIR / "media"