# Generated by Django 5.2.5 on 2025-10-03 00:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_management', '0004_courselesson'),
        ('lesson_management', '0002_lessonenrollment'),
        ('student_management', '0005_enrollmentsequence_alter_student_course_and_more'),
        ('teachersManagement', '0003_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='Duration in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='course_management.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='lesson_management.lesson')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='teachersManagement.teacherprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='classroom_and_grading.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_enrolments', to='student_management.student')),
            ],
            options={
                'ordering': ['student'],
            },
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('course', 'lesson', 'teacher', 'start_date'), name='uniq_classroom_slot_per_teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomstudent',
            unique_together={('classroom', 'student')},
        ),
    ]
