# Generated by Django 5.2.5 on 2025-10-03 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_and_grading', '0001_initial'),
        ('student_management', '0005_enrollmentsequence_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomstudent',
            options={'ordering': ['student__id']},
        ),
        migrations.RenameField(
            model_name='classroomstudent',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.RemoveField(
            model_name='classroomstudent',
            name='status',
        ),
        migrations.AlterField(
            model_name='classroomstudent',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='classroom_and_grading.classroom'),
        ),
        migrations.AlterField(
            model_name='classroomstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_rosters', to='student_management.student'),
        ),
    ]
