# Generated by Django 5.2.5 on 2025-10-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_and_grading', '0002_alter_classroomstudent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomstudent',
            options={'ordering': ['student_id']},
        ),
    ]
