# Generated by Django 5.2.5 on 2025-10-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_and_grading', '0003_alter_classroomstudent_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='duration_days',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
