# Generated by Django 5.2.5 on 2025-10-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_and_grading', '0004_remove_classroom_duration_days_and_more'),
    ]

    operations = [
    ]
