# Generated by Django 5.2.5 on 2025-10-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_and_grading', '0005_populate_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
