# Generated by Django 5.2.5 on 2025-10-04 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_and_grading', '0007_alter_classroom_end_date'),
        ('lesson_management', '0003_lesson_youtube_link_lesson_youtube_thumbnail_and_more'),
        ('student_management', '0005_enrollmentsequence_alter_student_course_and_more'),
        ('teachersManagement', '0003_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_awarded', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='lesson_management.assignment')),
                ('graded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_grades', to='teachersManagement.teacherprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_grades', to='student_management.student')),
            ],
            options={
                'ordering': ['student_id'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
