# Generated by Django 5.2.5 on 2025-10-17 21:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom_and_grading", "0008_assignmentgrade"),
        ("teachersManagement", "0004_add_teacher_display_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentgrade",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="given_grades",
                to="teachersManagement.teacherprofile",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentgrade",
            name="marks_awarded",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
