# Generated by Django 5.2.5 on 2025-10-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom_and_grading", "0009_make_assignmentgrade_fields_nullable"),
        ("course_management", "0008_course_director_name"),
        ("lesson_management", "0009_lessoncreditawarded"),
        ("teachersManagement", "0004_add_teacher_display_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentgrade",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_grades",
                to="teachersManagement.teacherprofile",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="classrooms", to="course_management.course"
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="classrooms", to="lesson_management.lesson"
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="teachersManagement.teacherprofile",
            ),
        ),
    ]
